#!/usr/bin/env python
import os
from clod.wsgi import application
try:
    from gevent import wsgi
except ImportError:
    import sys
    print >>sys.stderr, "You need to include gevent before you can use this"
    print >>sys.stderr, "    pip install gevent"
    sys.exit(1)


if __name__ == '__main__':
    PORT = 8088 if not "CLOD_PORT" in os.environ else int(os.environ['CLOD_PORT'])
    HOST = '0.0.0.0' if not 'CLOD_HOST' in os.environ else os.environ['CLOD_HOST']
    print "Listening on %s:%d" % (HOST, PORT)
    try:
        wsgi.WSGIServer((HOST, PORT), application, spawn=None).serve_forever()
    except KeyboardInterrupt:
        print "Thanks for using and abusing me!"
